### ISSUE TITLE
AssertionError: Postprocessor/convert_scores is not in graph

### ISSUE THREAD

**Issue by mj13qi** [GustavZ/realtime_object_detection#11]
Hi GustavZ 
  I try this on my jetson-tx2 and it show this error.

`/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_gtk3agg.py:16: UserWarning: The Gtk3Agg backend is known to not work on Python 3.x with pycairo. Try installing cairocffi.
  "The Gtk3Agg backend is known to not work on Python 3.x with pycairo. "
Model found. Proceed.
Loading frozen model into memory
2018-03-22 12:57:30.670896: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:858] ARM has no NUMA node, hardcoding to return zero
2018-03-22 12:57:30.671162: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: NVIDIA Tegra X2 major: 6 minor: 2 memoryClockRate(GHz): 1.3005
pciBusID: 0000:00:00.0
totalMemory: 7.66GiB freeMemory: 1.76GiB
2018-03-22 12:57:30.671251: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: NVIDIA Tegra X2, pci bus id: 0000:00:00.0, compute capability: 6.2)
Traceback (most recent call last):
  File "/home/nvidia/realtime_object_detection-master/object_detection.py", line 301, in <module>
    main()
  File "/home/nvidia/realtime_object_detection-master/object_detection.py", line 295, in main
    graph, score, expand = load_frozenmodel()
  File "/home/nvidia/realtime_object_detection-master/object_detection.py", line 128, in load_frozenmodel
    assert d in name_to_node_map, "%s is not in graph" % d
AssertionError: Postprocessor/convert_scores is not in graph
`

What should I do?

**Comment by GustavZ** [comment]
You are not running an SSD_Mobilenet Model.
This is a problem caused by split_model.
Set it to False in the config then it will run but ofcourse you will not benefit of the speed increase
