### ISSUE TITLE
run_objectdetection can not be run  successfully

### ISSUE THREAD

**Issue by Programmerwyl** [GustavZ/realtime_object_detection#27]
The environment：jeston tx2:
opencv: 4.0.0
Camera: CSI Cameras
when I run run_objectdetection,it errors.

('frame', None)

Traceback (most recent call last):
  File "run_objectdetection.py", line 189, in <module>
    detection(model, config)
  File "run_objectdetection.py", line 84, in detection
    gpu_feeds = {image_tensor: vs.expanded()}
  File "/home/nvidia/Downloads/realtime_object_detection-master/rod/helper.py", line 220, in expanded
    return np.expand_dims(cv2.cvtColor(self.frame, cv2.COLOR_BGR2RGB), axis=0)
cv2.error: OpenCV(4.0.0-pre) /home/nvidia/opencv/modules/imgproc/src/color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'CvtHelper'

I find that  "frame = vs.read()" is always None.
If you have any ideas,please tell me .
Thanks !

**Comment by GustavZ** [comment]
@Programmerwyl 
are you using the current master?
1. how does your config look like?
2. Did you change code?
3. Which python / openCV /JetPack version are you using

**Comment by Programmerwyl** [comment]
@GustavZ Thank you very much for your reply.
yes ,it is the current master
I haven't changed anything about your code.
python 2.7 
opencv 4.0
jetpack 28.2

**Comment by GustavZ** [comment]
This is really strange as i just double checked everything today.
Which TensorFlow do you use?

**Comment by guoDebby** [comment]
I have the same problem, I'm using tensorflow1.6, opencv4.0, jetson Xavier.
Does anyone know how to fix it?

**Comment by sathees07** [comment]
how to solve this problem?
Traceback (most recent call last):
  File "objectdetection_image.py", line 20, in <module>
    main()
  File "objectdetection_image.py", line 16, in main
    model = ObjectDetectionModel(config).prepare_model(input_type)
  File "/home/nvidia/Downloads/realtime_object_detection-master (2)/rod/model.py", line 391, in prepare_model
    self.prepare_input_stream()
  File "/home/nvidia/Downloads/realtime_object_detection-master (2)/rod/model.py", line 366, in prepare_input_stream
    (self.config.WIDTH,self.config.HEIGHT)).start()
  File "/home/nvidia/Downloads/realtime_object_detection-master (2)/rod/helper.py", line 195, in start
    self.load_images()
  File "/home/nvidia/Downloads/realtime_object_detection-master (2)/rod/helper.py", line 202, in load_images
    if idx >=self.limit:
TypeError: unorderable types: int() >= str()
